### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: when importing project

### ISSUE THREAD

**Issue by paulvi** [codenvy/eclipse-plugin#116]
when importing https://codenvy.com/ws/codenvy-sdk/spring-gs-rest-service

I got

An internal error occurred during: "Configure project".
com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.codenvy.eclipse.core.CodenvyProjectDescriptor] value failed: null

```
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.codenvy.eclipse.core.CodenvyProjectDescriptor] value failed: null
    at com.codenvy.eclipse.core.CodenvyProjectDescriptor.load(CodenvyProjectDescriptor.java:51)
    at com.codenvy.eclipse.core.CodenvyNature$1.run(CodenvyNature.java:72)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.codenvy.eclipse.core.CodenvyProjectDescriptor] value failed: null
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:440)
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:244)
    at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:167)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:385)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1071)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:268)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2144)
    at com.codenvy.eclipse.core.CodenvyProjectDescriptor.load(CodenvyProjectDescriptor.java:48)
    ... 2 more
Caused by: java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:192)
    at com.codenvy.eclipse.core.CodenvyProjectDescriptor.<init>(CodenvyProjectDescriptor.java:61)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:125)
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:240)
    ... 10 more

```

eclipse.buildId=4.4.1.M20140925-0400
java.version=1.8.0_05
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product org.eclipse.epp.package.java.product -showLocation
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -showLocation

**Comment by PathriK** [comment]
I too am getting this exception while importing an Android Project that I developed in Codenvy Cloud IDE. 

@paulvi Did you find any workaround for this issue?

**Comment by bmicklea** [comment]
@paulvi I'm trying to clean up some old issues, is this still occurring?
